# Pull Docker Hub base image
FROM node:latest
# Set working directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package*.json ./
RUN npm install
# Copy app to container
COPY . .
# Expose port to container
EXPOSE 3000

# Run the "dev" script in package.json
CMD ["npm", "run", "start"]