version: "3.7"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    restart: unless-stopped
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped
