version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    networks:
      - mern-network
    restart: unless-stopped
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    networks:
      - mern-network
    depends_on:
      - server
    restart: unless-stopped
networks:
  mern-network:
    driver: bridge