version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3001
    networks:
      - mern-network
    volumes:
      - ./server/src:/app/src
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
      - /usr/app/node_modules
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  mern-network:
    driver: bridge