# Pull Docker Hub base image
FROM node:latest
# Set working directory
WORKDIR /usr/src/app
# Install app dependencies
COPY package*.json ./
RUN npm install
# Copy app to container
COPY . .
# Expose port to container
EXPOSE 3001

RUN npm run build

# Run the "prod" script in package.json
CMD ["npm", "run", "start:prod"]